
# D:\Work\Python\sat-python\include\parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '1D13BFBB8B04FA25039CF9853D815AB9'
    
_lr_action_items = {'P_LINE':([0,],[2,]),'VARIABLE':([0,3,4,6,8,9,],[3,-6,8,9,-5,10,]),'$end':([0,1,3,4,5,7,8,10,],[-7,0,-6,-3,-4,-2,-5,-1,]),'CNF':([2,],[6,]),'TERMCHAR':([3,4,8,],[-6,7,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'variableList':([0,],[4,]),'empty':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> P_LINE CNF VARIABLE VARIABLE','start',4,'p_start','PyBool_dimacs_parse.py',43),
  ('start -> variableList TERMCHAR','start',2,'p_start','PyBool_dimacs_parse.py',44),
  ('start -> variableList','start',1,'p_start','PyBool_dimacs_parse.py',45),
  ('start -> empty','start',1,'p_start','PyBool_dimacs_parse.py',46),
  ('variableList -> variableList VARIABLE','variableList',2,'p_variableList','PyBool_dimacs_parse.py',65),
  ('variableList -> VARIABLE','variableList',1,'p_variableList','PyBool_dimacs_parse.py',66),
  ('empty -> <empty>','empty',0,'p_empty','PyBool_dimacs_parse.py',76),
]
